In [1]:
# Using this as an actual protein in the csv file to
# attempt to match the DSSP file in DataFraming.

In [2]:
# Importing Libraries
from biopandas.pdb import PandasPdb
import pandas as pd # About to change some options 
import numpy as np
# Prior to modifications 
# pd.options.display.max_rows
# Prints 60 as max rows
# pd.set_option("display.max_rows", None)
# print(pd.options.display.max_rows)

In [3]:
# Securely fetching the protein and displaying
ppdb = PandasPdb().fetch_pdb('1A2T')
ppdb.df['ATOM'].head()
df = pd.DataFrame(ppdb.df['ATOM'])

In [4]:
df.head()

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
0,ATOM,1,,N,,LEU,,A,7,,...,-0.503,37.453,21.068,1.0,53.40,,,N,NaN,375
1,ATOM,2,,CA,,LEU,,A,7,,...,0.788,36.714,21.079,1.0,48.40,,,C,NaN,376
2,ATOM,3,,C,,LEU,,A,7,,...,1.794,37.628,20.396,1.0,50.49,,,C,NaN,377
3,ATOM,4,,O,,LEU,,A,7,,...,1.407,38.624,19.799,1.0,54.51,,,O,NaN,378
4,ATOM,5,,CB,,LEU,,A,7,,...,0.639,35.386,20.331,1.0,44.96,,,C,NaN,379

In [5]:
def organizeddf(df):
    df1 = df.copy()
    del_cols = ['blank_1', 'alt_loc', "blank_2", 'insertion'
               ,'blank_3', 'occupancy', 'x_coord', 'y_coord', 'z_coord'
               ,'blank_4', 'segment_id', 'charge', 'line_idx']
    sorted_cols = ['record_name', 'atom_name', 'element_symbol', 'residue_name', 'chain_id'
                  ,'residue_number','b_factor']
# This command successfully drops those listed columns
    df1.drop(labels = del_cols,inplace=True, axis=1)
    df1.set_index('atom_number', inplace=True)
    df1 = df1[sorted_cols]
    return df1

In [15]:
df1 = organizeddf(df)
df1.head(20)

,record_name,atom_name,element_symbol,residue_name,chain_id,residue_number,b_factor
atom_number,,,,,,,
1,ATOM,N,N,LEU,A,7,53.40
2,ATOM,CA,C,LEU,A,7,48.40
3,ATOM,C,C,LEU,A,7,50.49
4,ATOM,O,O,LEU,A,7,54.51
5,ATOM,CB,C,LEU,A,7,44.96
6,ATOM,CG,C,LEU,A,7,39.75
7,ATOM,CD1,C,LEU,A,7,36.61
8,ATOM,CD2,C,LEU,A,7,37.86
9,ATOM,N,N,HIS,A,8,50.58
10,ATOM,CA,C,HIS,A,8,49.59
11,ATOM,C,C,HIS,A,8,45.25
12,ATOM,O,O,HIS,A,8,43.75
13,ATOM,CB,C,HIS,A,8,57.60
14,ATOM,CG,C,HIS,A,8,70.89
15,ATOM,ND1,N,HIS,A,8,77.91
16,ATOM,CD2,C,HIS,A,8,77.90
17,ATOM,CE1,C,HIS,A,8,80.45
18,ATOM,NE2,N,HIS,A,8,81.34
19,ATOM,H,H,HIS,A,8,0.00
20,ATOM,HD1,H,HIS,A,8,0.00

In [7]:
path = '''/home/sanctus/Git/Proteomics-Research/data/csv
'''
df1a2t = df1.copy()
df1a2t.residue_number.fillna(value=('NaN'))
df1a2t.shape

(1337, 7)

In [16]:
# Returns a data conditioned DF
dfstd = organizeddf(df)
resbdf = dfstd.iloc[:,5:6]
resbdf['residue_number']
residues = resbdf['residue_number'].fillna(0)
print(residues)
#print(residues)
#print(type(residues))
# residues values as full numpy array 
residx = resbdf['residue_number'].unique()
print(residx)
# print(residues) prints all full values as an numpy array
# rescount = pd.Series(data = residues, )
# residues2 just gives me the length of the array of unique elements
# residues2 = resbdf['residue_number'].nunique()
resdfIdx = pd.Index(residx)
resdfval = pd.Series(residues)
#print(resdfIdx)
resdfcounts = resdfval.value_counts()
print(resdfcounts) # This prints out an unsorted index of unique values with the number of index rows it occupies.

atom_number
1         7
2         7
3         7
4         7
5         7
6         7
7         7
8         7
9         8
10        8
11        8
12        8
13        8
14        8
15        8
16        8
17        8
18        8
19        8
20        8
21        8
22        9
23        9
24        9
25        9
26        9
27        9
28        9
29        9
30        9
       ...
1319    139
1320    139
1321    139
1322    139
1323    139
1324    139
1325    140
1326    140
1327    140
1328    140
1329    140
1330    140
1331    140
1332    140
1333    140
1334    140
1335    140
1336    140
1337    140
1338    140
1339    140
1340    140
1341    141
1342    141
1343    141
1344    141
1345    141
1346    141
1347    141
1348    141
Name: residue_number, Length: 1337, dtype: int64
[  7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  24  25
  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61
  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115
 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133
 134 135 136 137 138 139 140 141]
81     17
105    17
87     17
35     17
126    17
140    16
115    14
91     14
27     14
85     14
113    14
93     14
54     14
71     13
78     13
70     13
64     13
84     13
63     13
28     13
53     13
49     13
97     13
24     13
48     13
110    13
46     13
16     13
45     13
134    13
       ..
66      8
104     8
99      8
42      7
11      7
117     7
47      7
56      7
31      7
109     6
132     6
90      6
94      6
130     6
102     6
69      6
12      6
17      6
60      6
112     6
58      6
50      5
55      5
86      5
29      5
107     5
20      5
79      5
88      5
96      5
Name: residue_number, Length: 134, dtype: int64

### Above shows the row and residue chain

In [10]:
dfrescounts = pd.DataFrame(data=resdfcounts, index=resdfIdx)
dfrescounts.head()

    residue_number
7                8
8               13
9               13
10              10
11               7

## Problem 1
### * Need to get the Average b_factor per residues
* List total number of unique items which should get  the total number of residues
* Do each of those have a set amount of do they differ?

In [11]:
# Lets try a unique count of of the items in that specific column first
dfrescounts.cumsum().head()
# Cumulative sum of unique residue vaues equals the number of rows of the original pdb
# This indicates that each atom in the protein has a residue assignment. None that are not assigned.

    residue_number
7                8
8               21
9               34
10              44
11              51

#### Total number of unique residues goes from 7 - 141, 134 total. 
* The residues have different amounts of atoms in them.
    * Need to find a way to grab those b factors.
        * Would be nice if it could be displayed in an array.
        * Not sure how to slice each set of differing residue numbers

In [25]:
# Using this DataFrame to show the b values.
resgroupbydf = dfstd.iloc[:,5:]
resgroupbydf.head(20)
# Creating a groupby object that groups by the different residue_number values as index with those appropriate
# b_factors
group = resgroupbydf['b_factor'].groupby(resgroupbydf['residue_number'])
# use b_factor values groups by residue number
group.groups
# Prints off the groupby object from Pandas and shows index rows.
# This explicitly specifies the rows of the DF to each residue unique value

{7: Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64', name='atom_number'),
 8: Int64Index([9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21], dtype='int64', name='atom_number'),
 9: Int64Index([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34], dtype='int64', name='atom_number'),
 10: Int64Index([35, 36, 37, 38, 39, 40, 41, 42, 43, 44], dtype='int64', name='atom_number'),
 11: Int64Index([45, 46, 47, 48, 49, 50, 51], dtype='int64', name='atom_number'),
 12: Int64Index([52, 53, 54, 55, 56, 57], dtype='int64', name='atom_number'),
 13: Int64Index([58, 59, 60, 61, 62, 63, 64, 65, 66], dtype='int64', name='atom_number'),
 14: Int64Index([67, 68, 69, 70, 71, 72, 73, 74, 75], dtype='int64', name='atom_number'),
 15: Int64Index([76, 77, 78, 79, 80, 81, 82, 83, 84], dtype='int64', name='atom_number'),
 16: Int64Index([85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97], dtype='int64', name='atom_number'),
 17: Int64Index([98, 99, 100, 101, 102, 103], dtype='int64', name='atom_number'),
 18: Int64Index([104, 105, 106, 107, 108, 109, 110, 111, 112], dtype='int64', name='atom_number'),
 19: Int64Index([113, 114, 115, 116, 117, 118, 119, 120, 121], dtype='int64', name='atom_number'),
 20: Int64Index([122, 123, 124, 125, 126], dtype='int64', name='atom_number'),
 21: Int64Index([127, 128, 129, 130, 131, 132, 133, 134, 135], dtype='int64', name='atom_number'),
 22: Int64Index([136, 137, 138, 139, 140, 141, 142, 143, 144], dtype='int64', name='atom_number'),
 24: Int64Index([156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168], dtype='int64', name='atom_number'),
 25: Int64Index([169, 170, 171, 172, 173, 174, 175, 176, 177], dtype='int64', name='atom_number'),
 26: Int64Index([178, 179, 180, 181, 182, 183, 184, 185, 186], dtype='int64', name='atom_number'),
 27: Int64Index([187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199,
             200],
            dtype='int64', name='atom_number'),
 28: Int64Index([201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213], dtype='int64', name='atom_number'),
 29: Int64Index([214, 215, 216, 217, 218], dtype='int64', name='atom_number'),
 30: Int64Index([219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230], dtype='int64', name='atom_number'),
 31: Int64Index([231, 232, 233, 234, 235, 236, 237], dtype='int64', name='atom_number'),
 32: Int64Index([238, 239, 240, 241, 242, 243, 244, 245, 246], dtype='int64', name='atom_number'),
 33: Int64Index([247, 248, 249, 250, 251, 252, 253, 254, 255], dtype='int64', name='atom_number'),
 34: Int64Index([256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267], dtype='int64', name='atom_number'),
 35: Int64Index([268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
             281, 282, 283, 284],
            dtype='int64', name='atom_number'),
 36: Int64Index([285, 286, 287, 288, 289, 290, 291, 292, 293], dtype='int64', name='atom_number'),
 37: Int64Index([294, 295, 296, 297, 298, 299, 300, 301, 302], dtype='int64', name='atom_number'),
 38: Int64Index([303, 304, 305, 306, 307, 308, 309, 310, 311], dtype='int64', name='atom_number'),
 39: Int64Index([312, 313, 314, 315, 316, 317, 318, 319], dtype='int64', name='atom_number'),
 40: Int64Index([320, 321, 322, 323, 324, 325, 326, 327, 328], dtype='int64', name='atom_number'),
 41: Int64Index([329, 330, 331, 332, 333, 334, 335, 336, 337], dtype='int64', name='atom_number'),
 42: Int64Index([338, 339, 340, 341, 342, 343, 344], dtype='int64', name='atom_number'),
 43: Int64Index([345, 346, 347, 348, 349, 350, 351, 352, 353, 354], dtype='int64', name='atom_number'),
 44: Int64Index([355, 356, 357, 358, 359, 360, 361, 362, 363], dtype='int64', name='atom_number'),
 45: Int64Index([364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376], dtype='int64', name='atom_number'),
 46: Int64Index([377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389], dtype='int64', name='atom_number'),
 47: Int64Index([390, 391, 392, 393, 394, 395, 396], dtype='int64', name='atom_number'),
 48: Int64Index([397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409], dtype='int64', name='atom_number'),
 49: Int64Index([410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422], dtype='int64', name='atom_number'),
 50: Int64Index([423, 424, 425, 426, 427], dtype='int64', name='atom_number'),
 51: Int64Index([428, 429, 430, 431, 432, 433, 434, 435], dtype='int64', name='atom_number'),
 52: Int64Index([436, 437, 438, 439, 440, 441, 442, 443, 444, 445], dtype='int64', name='atom_number'),
 53: Int64Index([446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458], dtype='int64', name='atom_number'),
 54: Int64Index([459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471,
             472],
            dtype='int64', name='atom_number'),
 55: Int64Index([473, 474, 475, 476, 477], dtype='int64', name='atom_number'),
 56: Int64Index([478, 479, 480, 481, 482, 483, 484], dtype='int64', name='atom_number'),
 57: Int64Index([485, 486, 487, 488, 489, 490, 491, 492, 493, 494], dtype='int64', name='atom_number'),
 58: Int64Index([495, 496, 497, 498, 499, 500], dtype='int64', name='atom_number'),
 59: Int64Index([501, 502, 503, 504, 505, 506, 507, 508], dtype='int64', name='atom_number'),
 60: Int64Index([509, 510, 511, 512, 513, 514], dtype='int64', name='atom_number'),
 61: Int64Index([515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526], dtype='int64', name='atom_number'),
 62: Int64Index([527, 528, 529, 530, 531, 532, 533, 534, 535], dtype='int64', name='atom_number'),
 63: Int64Index([536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548], dtype='int64', name='atom_number'),
 64: Int64Index([549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561], dtype='int64', name='atom_number'),
 65: Int64Index([562, 563, 564, 565, 566, 567, 568, 569, 570], dtype='int64', name='atom_number'),
 66: Int64Index([571, 572, 573, 574, 575, 576, 577, 578], dtype='int64', name='atom_number'),
 67: Int64Index([579, 580, 581, 582, 583, 584, 585, 586, 587, 588], dtype='int64', name='atom_number'),
 68: Int64Index([589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599], dtype='int64', name='atom_number'),
 69: Int64Index([600, 601, 602, 603, 604, 605], dtype='int64', name='atom_number'),
 70: Int64Index([606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618], dtype='int64', name='atom_number'),
 71: Int64Index([619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631], dtype='int64', name='atom_number'),
 72: Int64Index([632, 633, 634, 635, 636, 637, 638, 639, 640], dtype='int64', name='atom_number'),
 73: Int64Index([641, 642, 643, 644, 645, 646, 647, 648, 649, 650], dtype='int64', name='atom_number'),
 74: Int64Index([651, 652, 653, 654, 655, 656, 657, 658], dtype='int64', name='atom_number'),
 75: Int64Index([659, 660, 661, 662, 663, 664, 665, 666, 667, 668], dtype='int64', name='atom_number'),
 76: Int64Index([669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680], dtype='int64', name='atom_number'),
 77: Int64Index([681, 682, 683, 684, 685, 686, 687, 688, 689], dtype='int64', name='atom_number'),
 78: Int64Index([690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702], dtype='int64', name='atom_number'),
 79: Int64Index([703, 704, 705, 706, 707], dtype='int64', name='atom_number'),
 80: Int64Index([708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719], dtype='int64', name='atom_number'),
 81: Int64Index([720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732,
             733, 734, 735, 736],
            dtype='int64', name='atom_number'),
 82: Int64Index([737, 738, 739, 740, 741, 742, 743, 744, 745], dtype='int64', name='atom_number'),
 83: Int64Index([746, 747, 748, 749, 750, 751, 752, 753, 754], dtype='int64', name='atom_number'),
 84: Int64Index([755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767], dtype='int64', name='atom_number'),
 85: Int64Index([768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780,
             781],
            dtype='int64', name='atom_number'),
 86: Int64Index([782, 783, 784, 785, 786], dtype='int64', name='atom_number'),
 87: Int64Index([787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799,
             800, 801, 802, 803],
            dtype='int64', name='atom_number'),
 88: Int64Index([804, 805, 806, 807, 808], dtype='int64', name='atom_number'),
 89: Int64Index([809, 810, 811, 812, 813, 814, 815, 816, 817], dtype='int64', name='atom_number'),
 90: Int64Index([818, 819, 820, 821, 822, 823], dtype='int64', name='atom_number'),
 91: Int64Index([824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836,
             837],
            dtype='int64', name='atom_number'),
 92: Int64Index([838, 839, 840, 841, 842, 843, 844, 845, 846], dtype='int64', name='atom_number'),
 93: Int64Index([847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859,
             860],
            dtype='int64', name='atom_number'),
 94: Int64Index([861, 862, 863, 864, 865, 866], dtype='int64', name='atom_number'),
 95: Int64Index([867, 868, 869, 870, 871, 872, 873, 874, 875], dtype='int64', name='atom_number'),
 96: Int64Index([876, 877, 878, 879, 880], dtype='int64', name='atom_number'),
 97: Int64Index([881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893], dtype='int64', name='atom_number'),
 98: Int64Index([894, 895, 896, 897, 898, 899, 900, 901, 902], dtype='int64', name='atom_number'),
 99: Int64Index([903, 904, 905, 906, 907, 908, 909, 910], dtype='int64', name='atom_number'),
 100: Int64Index([911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921], dtype='int64', name='atom_number'),
 101: Int64Index([922, 923, 924, 925, 926, 927, 928, 929, 930, 931], dtype='int64', name='atom_number'),
 102: Int64Index([932, 933, 934, 935, 936, 937], dtype='int64', name='atom_number'),
 103: Int64Index([938, 939, 940, 941, 942, 943, 944, 945, 946], dtype='int64', name='atom_number'),
 104: Int64Index([947, 948, 949, 950, 951, 952, 953, 954], dtype='int64', name='atom_number'),
 105: Int64Index([955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967,
             968, 969, 970, 971],
            dtype='int64', name='atom_number'),
 106: Int64Index([972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983], dtype='int64', name='atom_number'),
 107: Int64Index([984, 985, 986, 987, 988], dtype='int64', name='atom_number'),
 108: Int64Index([989, 990, 991, 992, 993, 994, 995, 996, 997], dtype='int64', name='atom_number'),
 109: Int64Index([998, 999, 1000, 1001, 1002, 1003], dtype='int64', name='atom_number'),
 110: Int64Index([1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014,
             1015, 1016],
            dtype='int64', name='atom_number'),
 111: Int64Index([1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024], dtype='int64', name='atom_number'),
 112: Int64Index([1025, 1026, 1027, 1028, 1029, 1030], dtype='int64', name='atom_number'),
 113: Int64Index([1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041,
             1042, 1043, 1044],
            dtype='int64', name='atom_number'),
 114: Int64Index([1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052], dtype='int64', name='atom_number'),
 115: Int64Index([1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063,
             1064, 1065, 1066],
            dtype='int64', name='atom_number'),
 116: Int64Index([1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077,
             1078, 1079],
            dtype='int64', name='atom_number'),
 117: Int64Index([1080, 1081, 1082, 1083, 1084, 1085, 1086], dtype='int64', name='atom_number'),
 118: Int64Index([1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097], dtype='int64', name='atom_number'),
 119: Int64Index([1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108], dtype='int64', name='atom_number'),
 120: Int64Index([1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117], dtype='int64', name='atom_number'),
 121: Int64Index([1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128,
             1129, 1130],
            dtype='int64', name='atom_number'),
 122: Int64Index([1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140], dtype='int64', name='atom_number'),
 123: Int64Index([1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151,
             1152],
            dtype='int64', name='atom_number'),
 124: Int64Index([1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163,
             1164, 1165],
            dtype='int64', name='atom_number'),
 125: Int64Index([1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174], dtype='int64', name='atom_number'),
 126: Int64Index([1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185,
             1186, 1187, 1188, 1189, 1190, 1191],
            dtype='int64', name='atom_number'),
 127: Int64Index([1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202,
             1203, 1204],
            dtype='int64', name='atom_number'),
 128: Int64Index([1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212], dtype='int64', name='atom_number'),
 129: Int64Index([1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222], dtype='int64', name='atom_number'),
 130: Int64Index([1223, 1224, 1225, 1226, 1227, 1228], dtype='int64', name='atom_number'),
 131: Int64Index([1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239,
             1240],
            dtype='int64', name='atom_number'),
 132: Int64Index([1241, 1242, 1243, 1244, 1245, 1246], dtype='int64', name='atom_number'),
 133: Int64Index([1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257,
             1258, 1259],
            dtype='int64', name='atom_number'),
 134: Int64Index([1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270,
             1271, 1272],
            dtype='int64', name='atom_number'),
 135: Int64Index([1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282], dtype='int64', name='atom_number'),
 136: Int64Index([1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293,
             1294, 1295],
            dtype='int64', name='atom_number'),
 137: Int64Index([1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304], dtype='int64', name='atom_number'),
 138: Int64Index([1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315], dtype='int64', name='atom_number'),
 139: Int64Index([1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324], dtype='int64', name='atom_number'),
 140: Int64Index([1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335,
             1336, 1337, 1338, 1339, 1340],
            dtype='int64', name='atom_number'),
 141: Int64Index([1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348], dtype='int64', name='atom_number')}

### Applying operation on the group to obtain results for each individual residue number.

In [48]:
group.sum().head(10)
# Hand calculated res 7 and obtained 365.98 from the values.
# This groupby function seems to work appropriately.
print(group.mean().head(10))
# Mean gives appropriate answer as well.
print(type(group.mean()))
# Type is a Pandas Series.

residue_number
7     45.747500
8     48.866154
9     27.430769
10    37.422000
11    34.125714
12    26.063333
13    23.567778
14    28.446667
15    30.510000
16    30.486154
Name: b_factor, dtype: float64
<class 'pandas.core.series.Series'>

### Outputting for verifiable results, will optimize code in future.

In [39]:
# Using to_csv 
Avgbfac1a2t = group.mean()
df1a2tavgb = pd.DataFrame(Avgbfac1a2t)
df1a2tavgb.head()

                 b_factor
residue_number
7               45.747500
8               48.866154
9               27.430769
10              37.422000
11              34.125714

In [49]:
df1a2tavgb.to_csv('Avgbfac1a2t.csv')
# Confirmed this file was there with ls. 
# File is readable!
df1a2tavgb.to_excel('Avgbfac1a2t.xlsx')
# Had to install openpyxl into the PP3 venv to get this to write to excel
# Excel file is created for this dict.

'1a2t DataFraming.ipynb'
 Avgbfac1a2t.csv
 Avgbfac1a2t.xlsx
'Biopandas Dataframing.ipynb'
'Biopandas Dataframing Jason.ipynb'
'Datamining PDB for Computations.ipynb'
'Reading and Extracting DSSP file information.ipynb'